steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/appdev-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/appdev-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/appdev-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/appdev-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'appdev-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/appdev-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  # Use Cloud Logging only (fixes the service account logs bucket issue)
  # This option allows you to use a service account without specifying logs_bucket
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

images:
  - 'gcr.io/$PROJECT_ID/appdev-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/appdev-backend:latest'
